### ISSUE TITLE
Refresh na iOS16.0.2 - vše zčerná

### ISSUE THREAD

**Issue by randolfCZ** [Lopdo/iRouming#3]
Ahoj, po upgrade na iOS16.0.2 / iPhone SE2 při “potažení prstem dolů” pro refresh / stažení nových věci daná obrazovka zčerná. Platí pro kteroukoli z nich, ať už obrázky/vtipy/videa/…
Po restartu aplikace je to zase OK.
Reinstalace aplikace nepomohla.

**Comment by Lopdo** [comment]
Vdaka za nahlasenie, pozrem sa na to

**Comment by Lopdo** [comment]
uz by to malo byt fixnute, mohol by si to prosim skusit?

**Comment by randolfCZ** [comment]
Works for me! :)
Diky moc!
